# Generated by Django 5.1 on 2024-08-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='nurseries.city')),
            ],
        ),
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('accepts_special_needs', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurseries', to='nurseries.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('vedio', models.FileField(upload_to='vedios/')),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurseries.nursery')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('age_min', models.IntegerField(default=2)),
                ('age_max', models.IntegerField(default=5)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='nurseries.nursery')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('specializations', models.TextField()),
                ('experience', models.TextField()),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurseries.nursery')),
            ],
        ),
    ]
