# Generated by Django 5.1 on 2024-08-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='vedio',
        ),
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='nursery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurseries.nursery'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='images/profile_default.jpg', upload_to='images/'),
        ),
    ]
