# Generated by Django 5.1 on 2024-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseries', '0002_remove_gallery_vedio_gallery_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='address',
            field=models.URLField(max_length=3000),
        ),
    ]
