# Generated by Django 5.1 on 2024-08-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseries', '0004_nursery_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
