# Generated by Django 5.1 on 2024-08-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseries', '0005_nursery_rejection_reason_nursery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='commercial_registry_file',
            field=models.FileField(blank=True, null=True, upload_to='commercial_registry/'),
        ),
        migrations.AddField(
            model_name='nursery',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='nursery_licenses/'),
        ),
    ]
