# Generated by Django 5.1 on 2024-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseries', '0007_alter_nursery_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='age_unit',
            field=models.CharField(choices=[('months', 'أشهر'), ('years', 'سنوات')], default='years', max_length=10),
        ),
        migrations.AddField(
            model_name='nursery',
            name='max_age',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='nursery',
            name='min_age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='nursery',
            name='status',
            field=models.CharField(choices=[('pending', 'تحت المراجعه'), ('verified', 'موثق'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
    ]
