# Generated by Django 5.1 on 2024-08-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseries', '0009_remove_nursery_age_unit_nursery_max_age_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='main_image',
            field=models.ImageField(default='images/nursery_default.jpg', upload_to='images/'),
        ),
    ]
