# Generated by Django 5.1 on 2024-08-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurseries', '0010_nursery_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursery',
            name='max_age_unit',
        ),
        migrations.RemoveField(
            model_name='nursery',
            name='min_age_unit',
        ),
    ]
