# Generated by Django 5.1 on 2024-08-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_remove_child_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='first_name',
            field=models.CharField(default=None, max_length=124),
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(default=None, max_length=124),
        ),
    ]
