# Generated by Django 5.1 on 2024-08-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_child_first_name_child_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Allergy',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='child',
            name='Disease',
            field=models.TextField(default=None),
        ),
    ]
