# Generated by Django 5.1 on 2024-08-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_child_allergy_child_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='about',
            field=models.TextField(default=True),
        ),
    ]
