# Generated by Django 5.1 on 2024-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_alter_child_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Allergy',
            field=models.TextField(blank=True, default='لا يوجد'),
        ),
        migrations.AlterField(
            model_name='child',
            name='Disease',
            field=models.TextField(blank=True, default='لايوجد'),
        ),
        migrations.AlterField(
            model_name='child',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
    ]
