# Generated by Django 5.1 on 2024-08-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurseries', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='nurseries.nursery')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='parents.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_unit', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], max_length=10)),
                ('duration_number', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age_min', models.IntegerField(default=0)),
                ('age_max', models.IntegerField(default=5)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='nurseries.nursery')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='reviewing', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='parents.child')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registrations.subscription')),
            ],
        ),
    ]
