# Generated by Django 5.1 on 2024-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('reviewing', 'تحت المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('waiting_payment', 'بانتظار الدفع')], default='reviewing', max_length=30),
        ),
    ]
