# Generated by Django 5.1 on 2024-08-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_unit',
            field=models.CharField(choices=[('day', 'يوم'), ('week', 'اسبوع'), ('month', 'شهر'), ('year', 'سنه')], max_length=10),
        ),
    ]
