# Generated by Django 5.1 on 2024-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default=' ', max_length=1024),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default=' ', max_length=1024),
        ),
    ]
