# Generated by Django 5.1 on 2024-08-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_first_name_contact_last_name'),
        ('parents', '0004_child_allergy_child_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parent')),
            ],
        ),
    ]
