# Generated by Django 5.1 on 2024-08-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_web_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='5'),
        ),
    ]
